import bnb from "../assets/bnb.png";
import ecommerce from "../assets/ecommerce.png";
import lending from "../assets/lending.png";
import quizapp from "../assets/quizapp.png";

export const projects: Project[] = [
	{
		id: "asd",
		img: bnb,
		alt: "Ligao Laundry BnB System",
		title: "Ligao Laundry BnB Booking System",
		description: "A booking system for Ligao Laundry BnB",
		techs: [
			"ReactJS",
			"Next.js",
			"Supabase",
			"Formik",
			"Material UI",
			"Redux",
			"React Native",
		],
		hasApp: true,
		appRepo: "https://github.com/awyyyn/Ligao-Laundry-App",
		webRepo: "https://github.com/awyyyn/Ligao-Laundry-Administrator",
		appUrl: "",
		webUrl: "",
	},
	{
		id: "123",
		img: ecommerce,
		alt: "La commerce",
		title: "La commerce",
		description: "",
		techs: ["Next.js", "TypeScript", "Redux", "Sanity.io", "Tailwind CSS"],
		hasApp: false,
		appRepo: "",
		webRepo: "https://github.com/awyyyn/react-projects/tree/main/ecommerce",
		appUrl: "",
		webUrl: "",
	},
	{
		id: "1231",
		img: lending,
		alt: "lending system",
		title: "Bicol Amigo's Lending System",
		description: "",
		techs: [
			"React.js + Vite",
			"Tailwind CSS + Daisy UI",
			"Supabase",
			"React Native",
			"Redux",
		],
		hasApp: true,
		appRepo: "https://github.com/awyyyn/payment-system-admin",
		webRepo: "https://github.com/awyyyn/payment-system-admin",
		appUrl: "",
		webUrl: "",
	},
	{
		id: "13213",
		img: quizapp,
		alt: "quizapp",
		title: "Country Quiz App",
		description: "",
		hasApp: false,
		techs: ["Svelte + Vite", "Tailwind CSS ", "REST API", "TypeScript"],
		appRepo: "",
		webRepo: "https://github.com/awyyyn/country-quiz.git",
		appUrl: "",
		webUrl: "",
	},
];
