name: GH Pages CI

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: git config --global user.name "${{ secrets.REPOSITORY }}"
          git config --global user.email "${{ secrets.EMAIL }}"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run deploy --if-present
